[package]
name = "rs-tetris"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
bevy_prototype_lyon = "0.13.0"
bevy_utils = "0.16.1"
chrono = "0.4.41"
lazy_static = "1.5.0"
rand = "0.9.2"
